### ISSUE TITLE
Tests related to amendements’ contents are not passing everywhere

### ISSUE THREAD

**Issue by davidbgk** [betagouv/zam#9]
See https://github.com/betagouv/zam/pull/7#issuecomment-390936561 for details

It works on my machine™ but not on @ronnix one, probably related to the PDF parsing (which might be outdated once the aspirateur is connected).

**Comment by davidbgk** [comment]
@ronnix can you check that it still fails against `master`?

**Comment by ronnix** [comment]
Still getting a bunch of failures but I feel it's data related. Not sure I'm giving the expected inputs in the env vars...
```
tests/test_models.py .......                                                                                                                                               [ 35%]
tests/test_output.py .FFF.FFFF..                                                                                                                                           [ 90%]
tests/test_utils.py ..                                                                                                                                                     [100%]
```
